### ISSUE TITLE
Unable to exit with non-Latin keyboard layouts

### ISSUE THREAD

**Issue by s-tdh** [porridge/bambam#38]
After the latest release I tried bambam with a Greek keyboard layout.  Greek letters appear, nice.  But as the user is now unable to type 'quit' (the program reads ";θιτ"), she/he would need to kill it from a tty.
-*-
I know a couple of kids that had a good time mashing my keyboard.  Thanks for this game!

**Comment by porridge** [comment]
Thank you for the report. I think this highlights the need for proper i18n. Perhaps I will have time for this towards the end of the year, but no promises.

Patches most welcome!

**Comment by porridge** [comment]
@s-tdh The latest version, https://github.com/porridge/bambam/releases/tag/v1.1.0 adds proper internationalization support.

Now I need your help in order to make the program speak Greek. Ideally, a PR which copies `bambam.pot` into `po/el.po` adding translations. See https://github.com/porridge/bambam/commit/1e5ff785c0ab0bd0d7192421f5f9890bb1f19b07#diff-9161a6222bcc9c0d0ecd9e96cfe790439400b21f02695c8ba265267d89d6ab91 for what I did for Polish translation.

Please don't hesitate to let me know if anything is unclear

**Comment by porridge** [comment]
FTR, translations can also be added via Weblate at https://hosted.weblate.org/projects/bambam/

**Comment by porridge** [comment]
Would "έξοδος" be a good quit command that is possible to type from a Greek keyboard layout?

**Comment by porridge** [comment]
FTR, it is possible to contribute a Greek translation via [weblate](https://hosted.weblate.org/projects/bambam/).

**Comment by porridge** [comment]
A few people contributed some non-latin translations and did not report any issues. So I'm assuming this is fixed in general, and closing this issue.
Supporting Greek specifically requires someone to contribute a translation, but it's not something I can do 😅
